services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: developer-portfolio-dev
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped

  prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: developer-portfolio
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped

volumes:
  node_modules:
